function onCreatePost()
    setProperty('gf.visible', false)
    makeAnimatedLuaSprite('Giant', 'Giant', 600, -200)
    addAnimationByPrefix('Giant', 'idle', 'TwitterGiant', 24, true)
    objectPlayAnimation('Giant', 'idle')
    addLuaSprite('Giant', false)
    makeLuaSprite('bg', 'MikoGradient', -600, -400)
    addLuaSprite('bg')
    scaleObject('bg', 1.15, 1.15)
    makeLuaSprite('audience', 'TargetAudience', 700, 540)
    addLuaSprite('audience')
    makeLuaSprite('pillar', 'Pillar', 100, 650)
    addLuaSprite('pillar')
    scaleObject('pillar', 1, 1)
    setObjectOrder('dadGroup','back')
    setObjectOrder('Giant','3')
    scaleObject('Giant', 1.15, 1.15)
    makeLuaSprite('the', nil, -400, -400)
    makeGraphic('the', 2000, 2000, 'A433FF')
    addLuaSprite('the')
    makeLuaSprite('the2', nil, -400, -400)
    makeGraphic('the2', 2000, 2000, 'FFFFFF')
    makeAnimatedLuaSprite('Minion', 'Minions', 350, 500)
    addAnimationByPrefix('Minion', 'idle', 'TwitterMinion', 24, true)
    objectPlayAnimation('Minion', 'idle')
    addLuaSprite('Minion', true)
    addLuaSprite('the2', true)
    setScrollFactor('the2', 0,0)
    setProperty('the2.alpha', 0)
    setProperty('Minion.visible', false)
    setProperty('audience.visible', false)
    setProperty('Giant.visible', false)
end
function onBeatHit() 
    if curBeat == 446 then
           doTweenAlpha('hudFunne', 'the2', 1, 0.6, 'quadIn')
    end
if curBeat == 448 then
    setProperty('Minion.visible', true)
    setProperty('audience.visible', true)
    setProperty('Giant.visible', true)
           doTweenAlpha('hudFunne', 'the2', 0, 1, 'quadIn')
end
end